services:
  mimir:
    image: grafana/mimir:latest
    ports:
      - "9009:9009"
    command: -config.file=/etc/mimir/mimir-config.yaml
    volumes:
      - ./mimir-config.yaml:/etc/mimir/mimir-config.yaml
    networks:
      - grafanet

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - grafanet

  promtail:
    image: grafana/promtail:2.8.0
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - ./:/etc/promtail/
      - /var/log:/var/log
    networks:
      - grafanet

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    networks:
      - grafanet

networks:
  grafanet:
